version: "3.8"

networks:
  backend:
    driver: bridge

volumes:
  postgres-data:

services:

  postgres:
    container_name: java-task13
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass